site_name: Lectures on CS
docs_dir: src

theme:
  name: material
  language: ru
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tracking
    - navigation.path
    # - navigation.indexes
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: red
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: light
      primary: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

nav:
  - Home: index.md
  - Лекции:
      - Лекция 1: 
          - lectures/lecture_one/index.md
          - lectures/lecture_one/analog_vs_digital.md
          - lectures/lecture_one/alphabet_power.md
          - lectures/lecture_one/measurement_confusion.md
          - lectures/lecture_one/binary_encoding.md
          - lectures/lecture_one/unique_decoding.md
          - lectures/lecture_one/binary_arithmetic.md
          - lectures/lecture_one/basic_logic_elements.md
          - lectures/lecture_one/functional_completeness.md

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
